---

- name: tasks
  hosts: all
  become: true
  tasks:
    - name: setup dns servers
      include_tasks: "../tasks/setup-resolv.yml"

- hosts: all
  become: true
  vars_files:
    - "../vars/rh-base.yml"
  roles:
    - bertvv.rh-base


- hosts: dns1
  become: true
  vars_files:
    - "../vars/dns.yml"
    - "../vars/dns1.yml"
  roles:
    - bertvv.bind

- hosts: dns2
  become: true
  vars_files:
    - "../vars/dns.yml"
    - "../vars/dns2.yml"
  roles:
    - bertvv.bind
